[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "html5lib>=1.1",
    "lxml>=6.0.2",
    "numpy>=2.4.2",
    "openai>=2.26.0",
    "pandas>=2.3.3",
    "pillow>=12.2.0",
    "plotly>=6.5.2",
    "psycopg2-binary>=2.9.11",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "statsmodels>=0.14.6",
    "streamlit>=1.54.0",
    "tornado>=6.5.5",
]
